### ISSUE TITLE
Cherry MX/Topre

### ISSUE THREAD

**Issue by fi0** [rsheldiii/openSCAD-projects#19]
Will there be an option for TMX stem? Or how should I modify this to support TMX?

**Comment by rsheldiii** [comment]
Hi there!

This library is designed to be modular, I would love to accept well structured PRs to add stems / key profiles / supports / etc. In order to make a tmx stem you'd want to make a `tmx.scad` file in `src/stems/` that defines the function `tmx_stem` that takes the values `depth` and `has_brim`, and add it to the selector in `/src/stems.scad`. settings can go in `/src/settings.scad` right next to the stuff for the alps and cherry stems, and a `tmx()` function can go in `src/key_transformations.scad`, but neither of those are required to get the shape working.

Depth tells you how tall the stem needs to be - bit of a misnomer, but I can refactor the name later - and has_brim tells you whether you should render a brim to help print the stem, which are custom to each stem currently. Then as long as the function renders a good shape and you enable the stem type, you should be able to use it with any key you define.

it looks like a tmx switch just needs a cylinder of a certain width? in which case this should be pretty easy to design! I don't have any tmx switches though, so it might be best for someone else to do, and then I can help with integrating to the rest of the code base

**Comment by rsheldiii** [comment]
gonna close this for now, if anyone wants to make one I'd love to incorporate it! I don't have any topre keyboards so I would be unable to test
