### ISSUE TITLE
The SA profile seems a bit... off.

### ISSUE THREAD

**Issue by thecakeisalie25** [rsheldiii/openSCAD-projects#20]
You got it pretty good in your first version, but the new version is a bit odd.
[OLD SA vs NEW SA](https://github.com/rsheldiii/openSCAD-projects/files/1742036/OLD.SA.vs.NEW.SA.zip)
(This isn't to say that this project is bad, in fact I think you're doing great, just that the profiles need a bit of work.)

**Comment by rsheldiii** [comment]
have you pulled since about 4 days ago? I found a bug with the tilt height that is since fixed in master: https://github.com/rsheldiii/openSCAD-projects/commit/17b0d8fc2061c2975ccfe34934dae99d80d4b2a3 SA should be pretty similar to V1, but I made a good few tweaks to the numbers after I got a reliable caliper

**Comment by thecakeisalie25** [comment]
Ah, no I haven't. That would do it, thanks!
